package qtrace

const (
	QlubCountry                   = "qlub.country"
	QlubCustomerEmail             = "qlub.customer.email"
	QlubDiningSessionID           = "qlub.dining_session_id"
	QlubHookAction                = "qlub.hook.action"
	QlubHookMethod                = "qlub.hook.method"
	QlubIntentID                  = "qlub.intent.id"
	QlubMetricSpan                = "qlub.metric"
	QlubOrderAmount               = "qlub.order.amount"
	QlubOrderID                   = "qlub.order_id"
	QlubOrderVAT                  = "qlub.order.vat"
	QlubPartyID                   = "qlub.party_id"
	QlubPaymentAmountBill         = "qlub.payment.amount.bill"
	QlubPaymentAmountBillNumber   = "qlub.payment.amount.bill.number"
	QlubPaymentAmountTip          = "qlub.payment.amount.tip"
	QlubPaymentAmountTipNumber    = "qlub.payment.amount.tip.number"
	QlubPaymentCommissionCustomer = "qlub.payment.commission.customer"
	QlubPaymentCommissionVendor   = "qlub.payment.commission.vendor"
	QlubPaymentCurrency           = "qlub.payment.currency"
	QlubPaymentFailed             = "qlub.payment.failed"
	QlubPaymentGateway            = "qlub.payment.gateway"
	QlubPaymentGatewayID          = "qlub.payment.gateway_id"
	QlubPaymentID                 = "qlub.payment.id"
	QlubPaymentOrderID            = "qlub.payment.order_id"
	QlubPaymentReference          = "qlub.payment.reference"
	QlubPaymentStatus             = "qlub.payment.status"
	QlubPaymentTxnID              = "qlub.payment.txn_id"
	QlubPosTriggered              = "qlub.pos.triggered"
	QlubPosVendor                 = "qlub.pos.vendor"
	QlubRequestPayload            = "qlub.request"
	QlubResponsePayload           = "qlub.response"
	QlubRestaurantUnique          = "qlub.restaurant_unique"
	QlubTableID                   = "qlub.table_id"
	QlubTableName                 = "qlub.table_name"
	QlubTableRevenueCenter        = "qlub.table_revenue_center"
	QlubTableSection              = "qlub.table_section"
	QlubWorkerResponse            = "qlub.pos.response"
)
